FROM python:3.7.3

RUN mkdir -p /tests/tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY resources/ /tests/resources/
COPY tools/ /tests/tools/

WORKDIR /tests

CMD [ "python3", "-u", "-m", "unittest", "discover", "-s", ".", "-p", "*.py" ]
